name       : kemoticons
version    : 5.42.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.42/kemoticons-5.42.0.tar.xz : 990b77c03604bc41adda924c7320049744cbda15ab8c255420ead9ce57b0ca38
license    :
    - CC-BY-4.0
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Convert text emoticons to graphical emoticons
description: |
    KEmoticons converts emoticons from text to a graphical representation with images in HTML. It supports setting different themes for emoticons coming from different providers.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kservice-devel
rundeps    :
    - devel :
        - kservice-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
