name       : kemoticons
version    : 5.81.0
release    : 49
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.81/kemoticons-5.81.0.tar.xz : ec8d17115c03c7a3071b4088478819c091cb3bb237a4fa7277e9e1ea9849fb9f
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Convert text emoticons to graphical emoticons
description: |
    KEmoticons converts emoticons from text to a graphical representation with images in HTML. It supports setting different themes for emoticons coming from different providers.
optimize   : lto
builddeps  :
    - karchive-devel
    - kservice-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
