name       : kemoticons
version    : 5.70.0
release    : 38
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.70/kemoticons-5.70.0.tar.xz : b9bf726d9dc8bda4c8a3fd5b053bffec9ac4dbc6293862d99124463b6cd66187
homepage   : https://community.kde.org/Frameworks
license    :
    - CC-BY-4.0
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Convert text emoticons to graphical emoticons
description: |
    KEmoticons converts emoticons from text to a graphical representation with images in HTML. It supports setting different themes for emoticons coming from different providers.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kservice-devel
rundeps    :
    - devel :
        - kservice-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
