name       : kemoticons
version    : 5.62.0
release    : 30
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.62/kemoticons-5.62.0.tar.xz : fab145b2c4106be8a4f0024cb436d02d0fdcbf8666e9a790cc1cd98db1e70313
license    :
    - CC-BY-4.0
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Convert text emoticons to graphical emoticons
description: |
    KEmoticons converts emoticons from text to a graphical representation with images in HTML. It supports setting different themes for emoticons coming from different providers.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kservice-devel
rundeps    :
    - devel :
        - kservice-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
