name       : kemoticons
version    : 5.74.0
release    : 41
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.74/kemoticons-5.74.0.tar.xz : 405c1d72ed812a6915276b9810e997b17572f7ecf66d58dea8869eed45da3702
homepage   : https://community.kde.org/Frameworks
license    :
    - CC-BY-4.0
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Convert text emoticons to graphical emoticons
description: |
    KEmoticons converts emoticons from text to a graphical representation with images in HTML. It supports setting different themes for emoticons coming from different providers.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kservice-devel
rundeps    :
    - devel :
        - kservice-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
