name       : kemoticons
version    : 5.44.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.44/kemoticons-5.44.0.tar.xz : 8ad694c4ec36a261ecc6ab7bc65e413e876747ab27e2ab5e9f072421f4f7fcbd
license    :
    - CC-BY-4.0
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Convert text emoticons to graphical emoticons
description: |
    KEmoticons converts emoticons from text to a graphical representation with images in HTML. It supports setting different themes for emoticons coming from different providers.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kservice-devel
rundeps    :
    - devel :
        - kservice-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
