name       : kemoticons
version    : 5.28.0
release    : 1
source     :
    - http://download.kde.org/stable/frameworks/5.28/kemoticons-5.28.0.tar.xz : dbaf7ba6814f8f7a5d00053aa452e2a8cd580738a0219702796be97570aa1d83
license    :
    - CC-BY-4.0
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : Convert text emoticons to graphical emoticons
description: |
    KEmoticons converts emoticons from text to a graphical representation with images in HTML. It supports setting different themes for emoticons coming from different providers.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kservice-devel
rundeps    :
    - devel :
        - kservice-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
